name: Dockerize Image Server

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build-container:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCK_USERNAME }}
        password: ${{ secrets.DOCK_PASSWD }}
    - name: Build and Push to Docker Hub
      uses: docker/build-push-action@v3
      with:
        context: ./server
        tags: techyfuzz123/feedback-server:latest, techyfuzz123/feedback-server:${{ github.run_number }}
        push: true
