name: Dockerize Image Server

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build-server:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCK_USERNAME }}
        password: ${{ secrets.DOCK_PASSWD }}
    - name: Setup buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and Push Server
      uses: docker/build-push-action@v3
      with:
        context: ./server
        tags: tamilarasug/feedback-server:latest, tamilarasug/feedback-server:${{ github.run_number }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

  build-client:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCK_USERNAME }}
        password: ${{ secrets.DOCK_PASSWD }}
    - name: Setup buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and Push Client
      uses: docker/build-push-action@v3
      with:
        context: ./client
        tags: tamilarasug/feedback-client:latest, tamilarasug/feedback-client:${{ github.run_number }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max